### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by DankMemeGuy** [ltsdw/gofile-downloader#9]
```
C:\Users\JUsername\Downloads\gofile-downloader-main>gofile-downloader.py https://gofile.io/d/Eiadkm
Traceback (most recent call last):
  File "C:\Users\JUsername\Downloads\gofile-downloader-main\gofile-downloader.py", line 34, in <module>
    class Main:
  File "C:\Users\JUsername\Downloads\gofile-downloader-main\gofile-downloader.py", line 35, in Main
    def __init__(self, url: str, password: str | None = None, max_workers: int = 5) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

I get that error code

**Comment by ltsdw** [comment]
Please see [you need at least python 3.10](https://github.com/ltsdw/gofile-downloader/issues/4#issuecomment-1223643143)

**Comment by DankMemeGuy** [comment]
I thought I did, guess not! Just updated and it worked like a charm!
